### ISSUE TITLE
Enhancement: Preserve state of original blocks

### ISSUE THREAD

**Issue by sebastianpech** [dvargas92495/roamjs-smartblocks#39]
It would be cool to have the original state of the block eg. collapsed or the query settings like "group by page" and "show paths" preserved after inserting a smart block.

I mostly insert queries on my DNP which slows roam down when they are visible. Also, I always have to manually change the query settings.

**Comment by dvargas92495** [comment]
Open state could be tackled as part of #22 

Query settings is something I would have to talk with the Roam to support. but thinking more broadly - why are queries something you are incorporating in a smartblock workflows? Most queries I have are meant to stay in one place

**Comment by sebastianpech** [comment]
About queries: Because stuff like between today and some other date only works on DNP pages. Of course, ideally, I would have all my queries collected on a separate page.

**Comment by dvargas92495** [comment]
For queries, we recommend checking out the QUERYBUILDER command now
