### ISSUE TITLE
Problem with TODOTODAY

### ISSUE THREAD

**Issue by palladion** [dvargas92495/roamjs-smartblocks#40]
Hi David, the <%TODOTODAY%> command gives different result between V1 and V2, if you already have tasks on the page. In V1 only tasks on other DNPs linked to the current DNP are entered, in V2 the tasks already on the current DNP are also entered as BlockRef again. See Screenshots.
<img width="695" alt="CleanShot 2021-08-26 at 13 31 53@2x" src="https://user-images.githubusercontent.com/3714399/130955513-751552e2-809a-484c-b03e-de3b6bd3aad3.png">
<img width="685" alt="CleanShot 2021-08-26 at 13 31 14@2x" src="https://user-images.githubusercontent.com/3714399/130955516-c378e38a-3fda-42d0-9676-07e268a91c12.png">

**Comment by forrestchang** [comment]
What does (({uid})) mean? I use `<%TODOOVERDUE:5,Today,-DROPPED%>` which is not working (Today & DROPPED are both tags).

**Comment by dvargas92495** [comment]
It's the format that the command uses to output the blocks. So try `<%TODOOVERDUE:5,(({uid})),Today,-DROPPED%>`
