### ISSUE TITLE
Different behavior on mouse and keyboard selections

### ISSUE THREAD

**Issue by harshadwaj** [dvargas92495/roamjs-smartblocks#41]
Steps to reproduce:

1. Create a smartblock with just this line of code
`window.document.querySelector("textarea.rm-block-input")`
2. Trigger once using `xx` and then selecting the smartblock from popup menu using mouse. It returns `null`.
3. Trigger again using `xx` and then selecting the smartblock from popup menu using keyboard. It returns the valid html element.
4. The above are repeatable again and again.

**Comment by dvargas92495** [comment]
I would say this is expected. when ou click enter, Roam's textarea it still focused. However, when you click, it blurs the input, which Roam then uses to replace the textarea with a div. 

What trouble is this causing?

**Comment by harshadwaj** [comment]
I am trying to get the block-id of the point where `xx` is triggered or the point where smartblock button is clicked. The existing code from 42SmartBlock behaves differently and returns non null result. It gives the block-id of the point of trigger. Whereas in Smartblock v2, it starts from a line below and returns null.

I am just trying to port the old code and its breaking. All I would want is the block-id of the point of trigger.

**Comment by dvargas92495** [comment]
Try the `CURRENTBLOCKREF` command

https://roamjs.com/extensions/smartblocks/command_reference#UtiLXpXUH
