### ISSUE TITLE
Error rendering settings

### ISSUE THREAD

**Issue by ViTuDia** [dvargas92495/roamjs-smartblocks#46]
The settings are not rendered, instead the message “error rendering settings” is shown.

**Comment by kevinhojae** [comment]
Same problem occurred to me. Can't change trigger keyword.

**Comment by Cheloneeh** [comment]
Same for me

**Comment by dvargas92495** [comment]
There should've been an update released last night to address this issue - can you refresh and see if you still see it?

**Comment by Cheloneeh** [comment]
I did a refresh, uninstalled the extension, cleared the local cache, refreshed again and installed the extension, but the error is still there

**Comment by dvargas92495** [comment]
Are you able to pop open the console and report what error is being thrown?

**Comment by ViTuDia** [comment]
<img width="996" alt="Screen Shot 2022-07-28 at 16 27 07" src="https://user-images.githubusercontent.com/59163092/181546621-c7d1f81b-5c20-4ec1-bcc4-25e82f16726a.png">

The plugin Query Builder shows the settings. This plugin is made by you (@dvargas92495) as wel isn't it? Maybe this clarifies something.

**Comment by dvargas92495** [comment]
It doesn't as I still don't know what the error is and the settings appear on my end. If you hit CMD+OPT+I to open the developer tools and go to console, what are the red messages that appear?

**Comment by ViTuDia** [comment]
<img width="747" alt="Screen Shot 2022-07-29 at 09 20 50" src="https://user-images.githubusercontent.com/59163092/181705339-96b1321e-2444-434e-9dae-45e8df1c2df7.png">

Let me know if you also need the log of this error.

**Comment by 8bitgentleman** [comment]
Running into the same error on a brand new install of smartblocks after a refresh. This error logs on every single keystroke for me
![image](https://user-images.githubusercontent.com/4028391/181779600-fb8d9226-6a10-4567-825f-9cf538785d99.png)

**Comment by dvargas92495** [comment]
Nice okay, I was able to reproduce and have it under review https://github.com/Roam-Research/roam-depot/pull/52

**Comment by ViTuDia** [comment]
Issue solved! Thanks!

**Comment by dvargas92495** [comment]
that would be unexpected since the change is still under review...
