### ISSUE TITLE
Hot Keys: Error with setting

### ISSUE THREAD

**Issue by ViTuDia** [dvargas92495/roamjs-smartblocks#47]
I get an error in the settings menu: Hot Keys. Is says: Error with setting. 

Attached a screenshot and console log.

<img width="807" alt="Screen Shot 2022-07-30 at 12 19 35" src="https://user-images.githubusercontent.com/59163092/181906041-a509979c-b183-481f-9a13-1f954d4a3b78.png">
<img width="765" alt="Screen Shot 2022-07-30 at 12 19 13" src="https://user-images.githubusercontent.com/59163092/181906046-be9b594c-31f8-41c7-b899-7a9aa59adb0a.png">
.

**Comment by dvargas92495** [comment]
Yup this is the same issue as #46 - it's not actually fixed yet bc the fix was still in review and hasn't been merged yet

The only thing that change was I asked the Roam team to scope the error handling down to the affected setting instead of the whole panel

**Comment by ViTuDia** [comment]
Solved.
