### ISSUE TITLE
DATE not building the right dates

### ISSUE THREAD

**Issue by blewa** [dvargas92495/roamjs-smartblocks#53]
Hey there,
I have a function to build out a weekly planning page with particular formatting.  For example, next week's should look like this:
`Week: 2023 Week 3 - Jan 23rd to Jan 27th`

My code to generate the date looks like this:
`Week: <%DATE:Next Monday,yyyy%> Week <%DATE:DBONW,w%> - <%DATE:Next Monday,MMM Qo%> to <%DATE:Next Friday,MMM Qo%>`

Here's what I see when I execute this code on Friday, Jan 20th:
`Week: 2023 Week 3 - Jan 1st to Jan 1st`

I've experimented with different functions to get future dates, but they're not returning accurate results.  Does this seem like a bug, or am I not escaping part of the call to DATE properly?  Thanks!

**Comment by dvargas92495** [comment]
The nlp might just not be detecting the `Next *day` correctly - what other permutations have you experimented with?

**Comment by blewa** [comment]
I've tried `DBONW`/`DBENW` as well but they return the same result.

I have other smartblocks where the feature works correctly using `Next Monday` and `Next Friday`, but with no other `<%DATE` calls on the same line.

**Comment by dvargas92495** [comment]
Oh so the issue only occurs when there's multiple `DATE` calls on the same line?

**Comment by blewa** [comment]
Yes, I just double checked and that looks like the case.

**Comment by mdroidian** [comment]
@blewa 

If you change the code to
`Week: <%DATE:Next Monday,yyyy%> Week <%DATE:DBONW,w%> - <%DATE:Next Monday,MMM do%> to <%DATE:Next Friday,MMM do%>`

(changing the `Qo` to `do`)

Does that give you the correct results?

**Comment by blewa** [comment]
It does!  Thank you!
