### ISSUE TITLE
Old version of smart block was used for daily notes

### ISSUE THREAD

**Issue by ssalka** [dvargas92495/roamjs-smartblocks#67]
I've been happily using SmartBlocks from RoamDepot for quite some time now, thank you David Vargas & any other contributors for making it work nicely.

However I recently updated my daily notes smart block, and today noticed that the old version was used. This seemed impossible to me, since the source of truth for the smart block is the Roam block in which it is defined, however the use of this old version somewhat contradicts that.

Are smart blocks I write being saved to another data store outside of Roam? I see in the code for this repo there are some DynamoDB references, if that is the case I have to reconsider future usage of this extension - I really don't want any of my Roam data, even simple SmartBlock definitions, to be exported anywhere except my local PC or Roam Research's own infrastructure. My assumption going in was that the automated filling out of daily notes was powered by Roam's API.

**Comment by dvargas92495** [comment]
Smartblocks are executed using Roam's API.

The only current use case of DynamoDB is the SmartBlock Store, where users opt in to sharing smartblocks. This feature never took off, and we may remove it entirely in favor of importing via [SamePage](https://samepage.network).

As for old versions being used, it's possible that either:
- There are other instances of the workflow with the same name in the graph. You could check the linked references of `SmartBlock`
- The Daily fired before your locally cached Roam Graph synced with Roam's backend.

**Comment by ssalka** [comment]
Thanks, I have only seen this happening around the time that I updated my SmartBlock, so perhaps it was the 2nd possibility. Closing this 🙏
