### ISSUE TITLE
CURRENTBLOCKREF creates fake references when not in first block

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roamjs-smartblocks#68]
from Jacob de Vera: [slack](https://roamresearch.slack.com/archives/C016N2B66JU/p1677600970632379)

## Example 1
![image](https://user-images.githubusercontent.com/3792666/222327186-ff89a2ce-726a-4e8c-bdb6-e9870e587a5e.png)
![image](https://user-images.githubusercontent.com/3792666/222327383-3c46a647-17b5-40fb-8dbc-39d7682a26b4.png)

## Example 2
![image](https://user-images.githubusercontent.com/3792666/222327149-169fec43-6f00-470c-aebb-eed70392156c.png)

## Example 3
![image](https://user-images.githubusercontent.com/3792666/222327451-42f9d18d-d3f3-482e-a66d-5d0c28c72fb4.png)

**Comment by mdroidian** [comment]
Fluxe report:
> here's a smartblock of mine that used to work as expected and is now having the same error. the first preserved block like this in my graph is from Jan 23rd, time stamps suggest that it was working on Jan 9th and that I manually adjusted the child block from Jan 16th

**Comment by dvargas92495** [comment]
Were you able to reproduce this issue? I see it still working on my end

**Comment by mdroidian** [comment]
I have

https://user-images.githubusercontent.com/3792666/222509882-f34d7e4f-0435-45d5-9c1d-e3bf2f3bdc4f.mp4

**Comment by mdroidian** [comment]
> User Fluxe reports this working on Jan 9th:
> 
> > here's a smartblock of mine that used to work as expected and is now having the same error. the first preserved block like this in my graph is from Jan 23rd, time stamps suggest that it was working on Jan 9th and that I manually adjusted the child block from Jan 16th

Checked out Dec 8th release https://github.com/dvargas92495/roamjs-smartblocks/commit/e2a083abf728689d4c5bdec8f72dc7da7de57801
Issue persisted

**Comment by dvargas92495** [comment]
Minimal Repro:
```
- #SmartBlock bug
    - <%IFVAR:hello,earth%> print me
    - <%CURRENTBLOCKREF:hello%> REf me!
    - <%GET:hello%> oh no
```
